dir_name = 'data_macro';
if ~exist(dir_name,'dir')
    mkdir(dir_name);
end
cd(dir_name);
data_file = strcat('data_macro_A_', num2str(mypara.A_c),...  % strcat('data_macro_A_', num2str(mypara.A_c, '%i'),...
    '_T_', num2str(round(time_current), '%i'),...
    '_dt_', num2str(time_step, '%.0e'),...
     '_Nx_', num2str(domain.x_number), ...
     '_r_', num2str(mypara.r0, '%.0e'), ...
     '_init_', num2str(mypara.dataID), ...
     '.mat');
if kk_time == time_step_number
    save(data_file, 'domain', 'mypara', 'myfunc', 'rho_current', ...
        'c_current', 'time_current', 'energy_record', 'energy_record_time');
else
    save(data_file, 'domain', 'mypara', 'myfunc', 'rho_current', ...
        'c_current', 'time_current');
end
cd ..