switch mypara.project
    case "macro"
        dir_name = 'data_2D_macro';
    case "kinetic"
        dir_name = 'data_2D_kinetic';
    otherwise
        warning('Unexpected project')
        pause
end
if ~exist(dir_name,'dir')
    mkdir(dir_name);
end
cd(dir_name);

switch mypara.project
    case "macro"
        data_file = strcat('data_2D_', mypara.project, ...
                            '_A_', num2str(mypara.A_c),... 
                            '_T_', num2str(time_current, '%.1f'),...
                            '_dt_', num2str(time_step, '%.0e'),...
                            '_Nx_', num2str(domain.x_number(1)), '_', num2str(domain.x_number(2)), ...
                            '_r_', num2str(mypara.r0, '%.0e'), ...
                            '_init_', num2str(mypara.init_ID), ...
                            '.mat');
        save(data_file, 'domain', 'mypara', 'myfunc', 'time_current', 'rho_current', 'c_current');
    case "kinetic"
        data_file = strcat('data_2D_', mypara.project, ...
                            '_A_', num2str(mypara.A_c),... 
                            '_eps_', num2str(mypara.eps, '%.0e'),...
                            '_T_', num2str(time_current, '%.1f'),...
                            '_dt_', num2str(time_step, '%.0e'),...
                            '_Nx_', num2str(domain.x_number(1)), '_', num2str(domain.x_number(2)), ...
                            '_r_', num2str(mypara.r0, '%.0e'), ...
                            '_init_', num2str(mypara.init_ID), ...
                            '.mat');
        save(data_file, 'domain', 'mypara', 'myfunc', 'time_current', 'rho_current', 'c_current');
    otherwise
        warning('Unexpected project')
        pause
end
cd ..